### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by mjac1521** [RogierW/rw-acme-client#11]
Hi Rogie,

I am using you rw-acme-client but when I run composer install this error popup 

Root composer.json requires rogierw/rw-acme-client ^1.0.9 -> satisfiable by rogierw/rw-acme-client[1.0.9].
- rogierw/rw-acme-client 1.0.9 requires php ^7.1 -> your php version (8.0.6) does not satisfy that requirement.

Sincerely Maykel

**Comment by RogierW** [comment]
Hi Maykel,

Sorry for the delayed response.

I haven't tested this client on php8.0 yet. I'm going to test it this week. If it runs without any issues I'll update the composer file.

I'll get back to you.

**Comment by RogierW** [comment]
@mjac1521 I finally had time to test it. You can now use this client on a system that has php8.0 installed.
