### ISSUE TITLE
Application for Pan domain name failed (无法申请泛域名证书)

### ISSUE THREAD

**Issue by amd5** [RogierW/rw-acme-client#12]
Application for Pan domain name failed

$order = $client->order()->new($account,['test.com','*.test.com']);

Please

**Comment by RogierW** [comment]
I don't see any question @amd5 ? 

I guess you want to use DNS for domain validation, based on the email you sent me. dns-01 is not implemented yet, as described in the readme file. I'd accept a PR for this.

**Comment by amd5** [comment]
dns-01 is not implemented yet&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;My need is this&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;thanks&nbsp;


  &nbsp;    
&nbsp;



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月3日(星期二) 晚上7:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RogierW/rw-acme-client] Application for Pan domain name failed (无法申请泛域名证书) (#12)





 
I don't see any question @amd5 ?
 
I guess you want to use DNS for domain validation, based on the email you sent me. dns-01 is not implemented yet, as described in the readme file. I'd accept a PR for this.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
