### ISSUE TITLE
Error on getBundle function

### ISSUE THREAD

**Issue by jdbravo** [RogierW/rw-acme-client#16]
I'm getting this error when I do $client->certificate()->getBundle($order);

Rogierw\RwAcme\Endpoints\Endpoint::createKeyId(): Argument #2 ($url) must be of type string, null given, called in /opt/www/iredmail-panel/vendor/rogierw/rw-acme-client/src/Endpoints/Certificate.php on line 14

If I print $orderData in getBundle function, $orderData->certificateUrl is null.

I'm wondering if I'm doing something wrong before getting the bundle:

This is the code I'm using for install/renew certificates:
function obtainCertificate($domain)
{
    $client = new Api(config('ssl.account'), storage_path('app/'.config('ssl.account_dir')), config('ssl.staging'));

    $hostname = config('ssl.subdomain') . "." . $domain;
    $hostnames = [$hostname];

    foreach(config('ssl.additional_subdomains') as $additionalSubdomain) {
        $hostnames[]=$additionalSubdomain."." . $domain;
    }

    if (!$client->account()->exists()) {
        $account = $client->account()->create();
    }

    $account = $client->account()->get();

    $order = $client->order()->new($account, $hostnames);

    $validationStatus = $client->domainValidation()->status($order);

    $privateKey = \Rogierw\RwAcme\Support\OpenSsl::generatePrivateKey();
    $csr = \Rogierw\RwAcme\Support\OpenSsl::generateCsr($hostnames, $privateKey);

    if (!isset($validationStatus[0])) {
        return [
            'result' => false,
            'error' => 'Can\'t get validation status'
        ];
    }

    // Validate domain
    if ($validationStatus[0]->status != 'valid') {
        $validationData = $client->domainValidation()->getFileValidationData($validationStatus);

        if (!is_array($validationData) || empty($validationData)) {
            return [
                'result' => false,
                'error' => 'Can\'t get the validation data'
            ];
        }

        $httpValidationData = $validationData[0];

        // Place challenge file
        Storage::disk('public')->put(config('ssl.challenge_dir') . "/" . $httpValidationData['filename'], $httpValidationData['content']);

        try {
            $client->domainValidation()->start($account, $validationStatus[0]);

            if ($order->isReady() && $client->domainValidation()->challengeSucceeded($order, DomainValidation::TYPE_HTTP)) {
                $client->order()->finalize($order, $csr);
            }

        } catch (DomainValidationException $exception) {
            return [
                'result' => false,
                'error' => 'The local HTTP challenge test has been failed: ' . $exception->getMessage()
            ];
        }
    }

    if (!$order->isFinalized()) {
        $client->order()->finalize($order, $csr);
    }

    $certificateBundle = $client->certificate()->getBundle($order);
    installCertificate($hostname, $certificateBundle, $privateKey, $csr);
    return [
        'result' => true,
        'error' => null
    ];

}

**Comment by RogierW** [comment]
Hi @jdbravo 
It looks like you're using the Laravel framework. What type of interface are you using to run this code? CLI or web server?

**Comment by RogierW** [comment]
Issue closed due to inactivity.
