### ISSUE TITLE
Error on setCertificateUrl

### ISSUE THREAD

**Issue by jdbravo** [RogierW/rw-acme-client#17]
In Order.php, line 90 ($orderData->setCertificateUrl($response->getBody()['certificate']);)  https://github.com/RogierW/rw-acme-client/blob/899df10b78948a19008aa761949591fd2ac23319/src/Endpoints/Order.php#L90 it's setting the certificate into $orderData, but that object is being encapsulated into that function, so it's not saving the certificate to any object that can be used later.

If you want to get the certificate you have to make another request. It should be a good idea to return $orderData in finalize function.

**Comment by RogierW** [comment]
The certificate URL will be available after you have finalized the order.
```
$order = $client->order()->new($account, [<domain>]);

$client->order()->finalize($order, $csr);
$order->certificateUrl // This will return something like https://acme-v02.api.letsencrypt.org/acme/cert/0323...
```

If you want to get the 'certificateUrl' later on, you can fetch the order by its ID and the certificateUrl will be set automatically. 

```
$order = $client->order()->get('<id>');

$order->certificateUrl // https://acme-v02.api.letsencrypt.org/acme/cert/0323...
```

I hope this helps you.

**Comment by RogierW** [comment]
Issue closed due to inactivity.
