### ISSUE TITLE
Private key doesn't match the certificate

### ISSUE THREAD

**Issue by nikolaysmeh** [RogierW/rw-acme-client#32]
After successfully obtaining the certificate files the comparing private key and certificate don't match

openssl x509 -in /path/to/yourdomain.crt -noout -modulus | openssl sha1
openssl rsa -in /path/to/your.key -noout -modulus | openssl sha1

These commands return different moduli.

**Comment by nikolaysmeh** [comment]
Problem solved.
I had to keep the private key generated for CSR and use it.

`
$privKeyFilename = $this->acmeClient->getAccountKeysPath() . 'privkey.pem';
openssl_pkey_export_to_file($privateKey, $privKeyFilename);
`

**Comment by RogierW** [comment]
That's correct. You'll need the private key to create a CSR, as described in the documentation: https://github.com/RogierW/rw-acme-client#generating-a-csr 

I assume that I can close this issue now.
