### ISSUE TITLE
not sure \Rogierw\RwAcme\DTO\OrderData::isReady should be cached..

### ISSUE THREAD

**Issue by divinity76** [RogierW/rw-acme-client#39]
I coded
```php
if (!$order->isReady()) {
    echo "Order is not ready yet";
    while (!$order->isReady()) {
        sleep(1);
        echo ".";
    }
}
```
After a while i thought "this is slower than expected.." and inspected the code, and realized that the value is cached forever.
Would be nice if isRead() was not cached, or at least had a cache timeout, or something?

**Comment by divinity76** [comment]
anyway i guess the api-user-solution is
```php
if (!$order->isReady()) {
    echo "Order is not ready yet";
    do {
        sleep(1);
        echo ".";
        $order = $client->order()->get($order->id);
    } while (!$order->isReady());
}
```
?

**Comment by RogierW** [comment]
Yes, that's correct. `$client->order()->get();` method returns a data object containing the order values at that specific moment. To 'refresh' those values, you need to create a new OrderData object by recalling `$client->order()->get()` method, like you suggested already.
